### ISSUE TITLE
Incompatibility with latest server-side changes

### ISSUE THREAD

**Issue by zeldovich** [meson800/touchstone-auth#5] opened 2023-05-04 17:32 UTC
It looks like the server-side code in Touchstone/Duo has changed in some way that makes `touchstone-auth` no longer work for me, as of a day or two ago.  Concretely, I get an error like:

    ...
      File "/home/nickolai/.local/lib/python3.11/site-packages/touchstone_auth/__init__.py", line 367, in perform_touchstone
        'parent': auth_html.find('input', {'id': 'js_parent'})['value'],
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    TypeError: 'NoneType' object is not subscriptable

This specific error is easy enough to fix, but there seem to be bigger changes in the expected auth flow that I haven't fully tracked down.  I'll probably try to dig into this at some point, when I get some free time, but I wanted to check if others are also seeing the same problem?

**Comment by meson800** [comment] 2023-05-04 18:48
I can reproduce, it no longer works for me. I think they are doing new serverside changes. Last week, Touchstone briefly switched to using a "frameless" Duo, which touchstone-auth worked great on. It looks like they did another change (and it's no longer frameless).

**Comment by meson800** [comment] 2023-05-04 19:43
@zeldovich try out version v0.5.2 (`pip install -U touchstone-auth`, fixed in b327a6e) I believe it fixes it, and please close if it does.

It looks like there is a new XSRF token we had to get, and weirdly Chrome user-agents don't work even with the new changes, so I switched to a Firefox user-agent (I've also been reverse-engineering with firefox). Too bad Duo is doing Evil Things (TM) by switching behavior based on user agent.

**Comment by zeldovich** [comment] 2023-05-04 19:59
Thanks!  This made it almost work; I had to add `auth=HTTPKerberosAuth()` to the `self._session.post(duo_auth_info['parent'], ...)` at the end of `perform_touchstone()`, at least for my case when using `KerberosAuth`.

**Closed as completed** 2023-05-05 00:23 UTC

**Comment by meson800** [comment] 2023-05-05 00:28
I just pushed v0.5.3, should be live now on PyPI

**Comment by zeldovich** [comment] 2023-05-05 00:31
Thanks again -- works great!
